//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topface1.TF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID_Product { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> ID_PodCategory { get; set; }
        public Nullable<int> ID_Supplier { get; set; }
        public Nullable<int> ID_ExpirationDate { get; set; }
    
        public virtual ExpirationDate ExpirationDate { get; set; }
        public virtual PodCategory PodCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
